$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: many-models-data-generation
compute: azureml:compute-instance-cluster

jobs:
  generate_step:
    type: parallel
    inputs:
      input_data:
        type: mltable
        path: azureml:base-series-seed:@latest
        mode: direct
    outputs:
      generated_data:
        type: uri_folder
        mode: rw_mount

    input_data: ${{inputs.input_data}}
    mini_batch_size: "30"
    resources:
      instance_count: 8
    max_concurrency_per_instance: 2
    mini_batch_error_threshold: 3
    retry_settings:
      max_retries: 2
      timeout: 300
    logging_level: "INFO"

    task:
      type: run_function
      code: "./src"
      entry_script: entry_script.py
      environment:
        conda_file: ./environment/conda_env.yml
        image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      program_arguments: "--output_path ${{outputs.generated_data}}"
      append_row_to: ${{outputs.generated_data}}
