name: mm-generation-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - pyarrow
      - mltable
      - azureml-core
      - azureml-dataset-runtime
      
